# Generated by Django 5.0.4 on 2024-04-16 01:50

import app_user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, validators=[app_user_app.validators.validate_name])),
                ('last_name', models.CharField(max_length=255, validators=[app_user_app.validators.validate_name])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
