# Generated by Django 5.0.4 on 2024-04-16 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_model_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_owners', models.IntegerField(null=True)),
                ('registration_number', models.CharField(unique=True)),
                ('manufacture_year', models.IntegerField()),
                ('number_of_doors', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('mileage', models.IntegerField()),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_model_app.carmodel')),
            ],
        ),
    ]
