# Generated by Django 5.0.4 on 2024-04-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_number', models.PositiveIntegerField(blank=True, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user_app.appuser')),
            ],
        ),
    ]
